import MainPage from "layout/main-page/MainPage";
import Head from "next/head";

const Home = () => {
	return (
		<div>
			<Head>
				<title>World Countries | Main Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<MainPage />
		</div>
	);
};

export default Home;
